name: Package NuGet
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Run Unit Tests and Coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build NuGet Package
        run: dotnet pack ./Bank.WebApi/Bank.WebApi.csproj -c Release -o ./nuget

      - name: Upload NuGet Package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./nuget/*.nupkg
