name: Snyk Analysis
env:
  DOTNET_VERSION: '9.x'
on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: snyk/actions/setup@master

      - name: Configurando la versión de .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Instalar Node.js y snyk-to-html
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g snyk-to-html

      - name: Run Snyk test and generate HTML report
        run: snyk code test --json | snyk-to-html -o snyk-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-html-report
          path: snyk-report.html
